### ISSUE TITLE
RPM meta data

### ISSUE THREAD

**Issue by faph** [edenhill/librdkafka#3949]
Description
===========

We're using the RPM packages from the Confluent repos. It appears that these packages are missing essential metadata. For example the packager information is missing and the changelog is no longer up to date.

How to reproduce
================

```
rpm -qp --changelog librdkafka1-1.9.0-1.cflt.el8.x86_64.rpm
```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.9.0`
 - [x] Apache Kafka version: 
 - [x] librdkafka client configuration: 
 - [x] Operating system: `RHEL 8`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by sharad1224** [comment]
RPM Solucation
