### ISSUE TITLE
Partition multiplexing use MessageImpl meta data 

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#839]
Description
===========
In the class  MessageImpl, there are many meta data fields that the consumer / producer can examine. If I use a multiplexing scheme to share one partition by a group of users, is it possible for the producer to send the message by adding the user id to the rd message meta data, then the consumer to check the user id from the rd message meta data to filter the message without going to the payload level?

Not quite sure if the rkmessage_->key can be used for that purpose. Or the msg_opaque can be used (What is the msg_opaque for?)

Thank you

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There are only two fields that makes it across the broker to the consumer:
 * Message Key
 * Message Value

The key is mainly used for partitioning and is typically suitable for the user id in your use-case.
